insert into bcfishobs.observations (
  observation_key         ,
  wbody_id                ,
  species_code            ,
  agency_id               ,
  point_type_code         ,
  observation_date        ,
  agency_name             ,
  source                  ,
  source_ref              ,
  utm_zone                ,
  utm_easting             ,
  utm_northing            ,
  activity_code           ,
  activity                ,
  life_stage_code         ,
  life_stage              ,
  species_name            ,
  waterbody_identifier    ,
  waterbody_type          ,
  gazetted_name           ,
  new_watershed_code      ,
  trimmed_watershed_code  ,
  acat_report_url         ,
  feature_code            ,
  linear_feature_id       ,
  wscode                  ,
  localcode               ,
  blue_line_key           ,
  watershed_group_code    ,
  downstream_route_measure,
  match_type              ,
  distances_to_stream     ,
  geom
)
select
  o.observation_key         ,
  o.wbody_id                ,
  o.species_code            ,
  o.agency_id               ,
  o.point_type_code         ,
  o.observation_date        ,
  o.agency_name             ,
  o.source                  ,
  o.source_ref              ,
  o.utm_zone                ,
  o.utm_easting             ,
  o.utm_northing            ,
  o.activity_code           ,
  o.activity                ,
  o.life_stage_code         ,
  o.life_stage              ,
  o.species_name            ,
  o.waterbody_identifier    ,
  o.waterbody_type          ,
  o.gazetted_name           ,
  o.new_watershed_code      ,
  o.trimmed_watershed_code  ,
  o.acat_report_url         ,
  o.feature_code            ,
  fwa.linear_feature_id       ,
  fwa.wscode_ltree as wscode                  ,
  fwa.localcode_ltree as localcode              ,
  fwa.blue_line_key           ,
  s.watershed_group_code    ,
  CEIL(GREATEST(s.downstream_route_measure, FLOOR(LEAST(s.upstream_route_measure, fwa.downstream_route_measure)))) as downstream_route_measure,
  fwa.match_type              ,
  fwa.distance_to_stream     ,
  whse_basemapping.FWA_LocateAlong(fwa.blue_line_key, CEIL(GREATEST(s.downstream_route_measure, FLOOR(LEAST(s.upstream_route_measure, fwa.downstream_route_measure))))) as geom
from bcfishobs.obs o
inner join bcfishobs.obs_fwa fwa on o.observation_key = fwa.observation_key
inner join whse_basemapping.fwa_stream_networks_sp s on fwa.linear_feature_id = s.linear_feature_id;

-- drop temp tables
--drop table bcfishobs.obs;
--drop table bcfishobs.obs_fwa;