name: bcfishobs-test
run-name: ${{ github.actor }} bcfishobs-testing
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  bcfishobs:
    runs-on: ubuntu-latest
    environment: testing
    container: ghcr.io/smnorris/bcfishpass:main
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Run bcfishobs
      run: |
        mkdir -p .make
        make -t .make/setup
        make -t .make/load_static
        make -t .make/fiss_fish_obsrvtn_pnt_sp
        make --debug=basic
        psql $DATABASE_URL -c "select * from bcfishobs.summary"